# Use the official JDK 21 image as the base
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file to the container
COPY target\springBoot-Rest_Api.jar /app/application.jar

# Expose the port your application runs on (modify if your application uses a different port)
EXPOSE 8080

# Command to run the JAR file
ENTRYPOINT ["java", "-jar", "/app/application.jar"]
