# Use the official JDK 21 image as the base
FROM openjdk:21-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file to the container
COPY target\onlineExamQuestions-0.0.1-SNAPSHOT.jar /app/application.jar

# Expose the port your application runs on (modify if your application uses a different port)
EXPOSE 9090

# Command to run the JAR file
ENTRYPOINT ["java", "-jar", "/app/application.jar"]
